# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0414bc8329227320edff61758cd6b1903cbe20f0f95883d1441c7adbc862ef2414d217b945b5604b63d73b4ae95c61ef9324366b3a07aba2a8fdfc376a4040d

test:
  secret_key_base: 0ba149a4ef0e29bafece0c08eb2d9fa3aa39f23e39e3235b65517bdaba4dc9d52f6d81b25651fcfdb7fefa2f65be2af4032c078fe0067e674cf8e2021806a492

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
